### ISSUE TITLE
Not really an issue on your part but been having this with crosshatch and coral

### ISSUE THREAD

**Issue by TheRingMaster** [ProtonAOSP/android_packages_apps_ElmyraService#4]
https://paste.ubuntu.com/p/c9dCbV6R8T/

Not complete sure what could be causing this issue.

**Comment by kdrag0n** [comment]
Your ROM has broken ContextHub, which is required for Active Edge. Build the CHRE daemon (`PRODUCT_PACKAGES += chre` should do the job) to fix it.

**Comment by TheRingMaster** [comment]
tyvm
